dist: trusty
language: java
jdk: oraclejdk8

sudo: required

services:
 - docker

before_install:
 - chmod +x gradlew
 - chmod +x script/docker_mssql_setup_script.sh
 
install:
 - ./script/docker_mssql_setup_script.sh
 - ./gradlew assemble

script:
 - ./gradlew check && ./gradlew integrationTest
 
after_success:
 - bash <(curl -s https://codecov.io/bash) -c -F unittests && bash <(curl -s https://codecov.io/bash) -c -F integration 
 
deploy:
  provider: script
  dry_run: false
  skip_cleanup: true 
  script: ./gradlew bintrayUpload 
  on: 
    tags: true
    branch: master
