dist: trusty
language: java
jdk: oraclejdk8
os: 
 - linux

services:
 - docker

before_install:
 - chmod +x gradlew
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - chmod +x script/docker_mssql_setup_script.sh
 - chmod +x script/docker_fuseki_setup_script.sh
 
install:
 - ./script/docker_mssql_setup_script.sh
 - ./script/docker_fuseki_setup_script.sh
 - ./gradlew assemble

script:
 - ./gradlew check && ./gradlew integrationTest
 
after_success:
 - bash <(curl -s https://codecov.io/bash) -c -F unittests && bash <(curl -s https://codecov.io/bash) -c -F integration 
 
deploy:
  provider: script
  edge: true
  script: ./gradlew bintrayUpload 
  on: 
    tags: true
    branch: master
