CREATE DATABASE testDb;
GO
USE testDb;

CREATE TABLE DEPT (
	DEPTNO int NOT NULL PRIMARY KEY, 
	DNAME varchar(30) NULL,
	LOC varchar(100) NULL, 
);

CREATE TABLE EMP (
	EMPNO int NOT NULL PRIMARY KEY, 
	ENAME varchar(100) NULL,
	JOB varchar(20) NULL, 
	DEPTNO int NULL FOREIGN KEY REFERENCES DEPT(DEPTNO)
);

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(10, 'APPSERVER', 'NEW YORK');

INSERT INTO EMP(EMPNO, ENAME, JOB, DEPTNO)
VALUES(7369, 'SMITH', 'CLERK', 10);