# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and run test with Gradle
      run: ./gradlew test
    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./build/reports/jacoco/test/jacocoTestReport.xml
        flags: unittests
        fail_ci_if_error: true
        
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Login Docker
      run: echo "{{$secrets.DOCKER_PASSWORD}}" | docker login -u "{{$DOCKER_USERNAME"}} --password-stdin
    - name: Setup SQL Server
      run: |
        chmod +x script/docker_mssql_setup_script.sh
        ./script/docker_mssql_setup_script.sh
    - name: Setup Setup Fuseki server
      run: |
        chmod +x script/docker_fuseki_setup_script.sh
        ./script/docker_fuseki_setup_script.sh
    - name: Build and run integration test (e2e) with Gradle
      run: ./gradlew integrationTest        
    - name: Upload integration test coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./build/reports/jacoco/integrationTestReport/integrationTestReport.xml
        flags: integration
        fail_ci_if_error: true
